# Generated by Django 4.2.22 on 2025-06-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0003_report_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(),
        ),
    ]
